{% set name = "prismatools" %}
{% set version = "0.1.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prismatools-{{ version }}.tar.gz
  sha256: 0694899863114e197109fb28a27a09d4ea1a69f0b04748b5c71daf008eab767d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - h5py
    - ipyleaflet
    - leafmap
    - numpy
    - rioxarray
    - xarray

test:
  imports:
    - prismatools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gthlor/prismatools
  summary: prismatools is an open-source Python package for reading, analyzing, and visualizing hyperspectral imagery from the PRISMA mission.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gthlor
